AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Slack User Management
Parameters:
    stage:
        Type: String
        AllowedValues:
          - alpha
          - beta
          - prod
        Description: Enter alpha, beta or prod to designate the deployment stage/environment
    notificationsEmail:
        Type: String
        AllowedPattern: "^[\\x20-\\x45]?[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"
        Description: Enter the email address of a person, group or system to be notified of alarms
    slackToken:
        Type: String
        Description: Slack Token
    azureTenantId:
        Type: String
        Description: Azure Tenant Id
    azureClientId:
        Type: String
        Description: Azure Client Id
    azureClientSecret:
        Type: String
        Description: Azure Client Secret
    layerBucket:
        Type: String
        Description: S3 bucket name containing Lambda layers

Globals:
    Function:
        Runtime: python3.6
        Handler: handler.handler
        MemorySize: 128
        Timeout: 30

Resources:
###
# Lambda functions
###
    layerMain:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: Grim-Reaper-Main
            Description: Main Python libraries for the Grim Reaper app
            ContentUri:
                Bucket: !Ref layerBucket
                Key: grim-reaper_layer.zip
            CompatibleRuntimes:
                - python3.6
            RetentionPolicy: Retain

    functionUserList:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "slack-user-reporter-userlist", !Ref stage ] ]
            Description: Generates a list of all slack users with non-disabled accounts
            CodeUri: ./sam/functions/slack-user-reporter-userlist
            Timeout: 900
            MemorySize: 1024
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBCrudPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
            Layers:
                - !Ref layerMain
            Environment:
                Variables:
                    SLACK_TOKEN: !Ref slackToken
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing

    functionAdLookup:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "slack-user-reporter-adlookup", !Ref stage ] ]
            Description: Looks up each Slack user against Azure AD
            CodeUri: ./sam/functions/slack-user-reporter-adlookup
            Timeout: 900
            MemorySize: 1536
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBCrudPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
            Layers:
                - !Ref layerMain
            Environment:
                Variables:
                    AZURE_TENANT_ID: !Ref azureTenantId
                    AZURE_CLIENT_ID: !Ref azureClientId
                    AZURE_CLIENT_SECRET: !Ref azureClientSecret
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing

    functionFinisher:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "slack-user-reporter-finisher", !Ref stage ] ]
            Description: Creates CSV and uploads to S3
            CodeUri: ./sam/functions/slack-user-reporter-finisher
            Timeout: 120
            MemorySize: 128
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBReadPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
                - S3CrudPolicy:
                    BucketName: !Ref s3Bucket
            Layers:
                - !Ref layerMain
            Environment:
                Variables:
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing
                    S3_BUCKET_NAME: !Ref s3Bucket

    s3Bucket:
        Type: AWS::S3::Bucket


###
# DynamoDB Tables
###

    dynamodbTableUserProcessing:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: uuid
                    AttributeType: "S"
                -
                    AttributeName: email
                    AttributeType: "S"
                -
                    AttributeName: status_code
                    AttributeType: "N"
            KeySchema:
                -
                    AttributeName: uuid
                    KeyType: HASH
                -
                    AttributeName: email
                    KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                -
                    IndexName: gsiStatusCode
                    KeySchema:
                        -
                            AttributeName: status_code
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL


###
# State Machine
###

    iamRoleStateMachineUserReporter:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    -
                        Effect: Allow
                        Principal:
                            Service: !Sub states.amazonaws.com
                        Action: "sts:AssumeRole"
            Path: "/"
            Policies:
                -
                    PolicyName: StatesExecutionPolicy
                    PolicyDocument:
                        Version: "2012-10-17"
                        Statement:
                            -
                                Effect: "Allow"
                                Action: "lambda:InvokeFunction"
                                Resource: "*"

    stateMachineUserReporter:
        Type: AWS::StepFunctions::StateMachine
        Properties:
            StateMachineName: !Join [ "-", [ "slack-user-reporter", !Ref stage ] ]
            DefinitionString:
                !Sub
                    - |-
                        {
                            "Comment": "Slack User Reporter",
                            "StartAt": "DetermineSlackUserCount",
                            "States": {
                                
                                "DetermineSlackUserCount": {
                                    "Type": "Task",
                                    "Comment": "Looks up Slack users and determines count",
                                    "Resource": "${functionUserListArn}",
                                    "ResultPath": "$",
                                    "Next": "AdLookup"
                                },
                                "AdLookup": {
                                    "Comment": "Query each user against Azure AD",
                                    "Type": "Task",
                                    "Resource": "${functionAdLookupArn}",
                                    "ResultPath": "$",
                                    "Next": "Finisher"
                                },
                                "Finisher": {
                                    "Comment": "Create CSV and send results to S3",
                                    "Type": "Task",
                                    "Resource": "${functionFinisherArn}",
                                    "End": true
                                
                                }
                            }
                        }
                    - {functionUserListArn: !GetAtt [ functionUserList, Arn ],
                        functionAdLookupArn: !GetAtt [ functionAdLookup, Arn ],
                        functionFinisherArn: !GetAtt [ functionFinisher, Arn ]}
            RoleArn: !GetAtt [ iamRoleStateMachineUserReporter, Arn ]


