AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API Gateway resources

Parameters:
    stage:
        Type: String

Resources:
    apigatewaySlack:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref stage
            DefinitionUri: ../../sam/api/slack-swagger.yaml


