AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda function resources

Parameters:
    stage:
        Type: String
    dynamodbTableUserProcessing:
        Type: String
    s3Bucket:
        Type: String

Globals:
    Function:
        Runtime: python3.7
        Handler: app.handler
        MemorySize: 128
        Timeout: 30

Resources:
    layerRequests:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: Grim-Reaper-Requests
            Description: Python requests library
            ContentUri: ../layers/requests
            CompatibleRuntimes:
                - python3.7
            RetentionPolicy: Delete

    layerXray:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: Grim-Reaper-Xray
            Description: Python aws_xray_sdk library for tracing
            ContentUri: ../layers/xray
            CompatibleRuntimes:
                - python3.7
            RetentionPolicy: Delete

    layerGrimreapercommon:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: Grim-Reaper-Common
            Description: Common code shared by all Grim Reaper functions
            ContentUri: ../layers/grimreaper_common
            CompatibleRuntimes:
                - python3.7
            RetentionPolicy: Delete

    functionUserList:
        Type: AWS::Serverless::Function
        Properties:
            Description: Generates a list of all slack users
            CodeUri: ../../sam/functions/grimreaper-userlist
            Timeout: 5
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBCrudPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
                - Statement:
                    -
                        Action: [ 'ssm:GetParameter', 'secretsmanager:GetSecretValue' ]
                        Effect: Allow
                        Resource: '*'
            Layers:
                - !Ref layerXray
                - !Ref layerRequests
                - !Ref layerGrimreapercommon
            Environment:
                Variables:
                    STAGE: !Ref stage
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing

    functionAdLookup:
        Type: AWS::Serverless::Function
        Properties:
            Description: Looks up each Slack user against Azure AD
            CodeUri: ../../sam/functions/grimreaper-adlookup
            Timeout: 180
            MemorySize: 256
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBCrudPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
                - Statement:
                    -
                        Action: [ 'ssm:GetParameter', 'secretsmanager:GetSecretValue' ]
                        Effect: Allow
                        Resource: '*'
            Layers:
                - !Ref layerXray
                - !Ref layerRequests
                - !Ref layerGrimreapercommon
            Environment:
                Variables:
                    STAGE: !Ref stage
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing

    functionSummarizer:
        Type: AWS::Serverless::Function
        Properties:
            Description: Summarizes user active/inactive split and generates S3 CSV
            CodeUri: ../../sam/functions/grimreaper-summarizer
            Timeout: 60
            MemorySize: 256
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBCrudPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
                - S3CrudPolicy:
                    BucketName: !Ref s3Bucket
            Layers:
                - !Ref layerXray
                - !Ref layerGrimreapercommon
            Environment:
                Variables:
                    STAGE: !Ref stage
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing
                    S3_BUCKET_NAME: !Ref s3Bucket

    functionSlackMessenger:
        Type: AWS::Serverless::Function
        Properties:
            Description: Sends messages to Slack for approvals, confirmations and notifications
            CodeUri: ../../sam/functions/grimreaper-slackmessenger
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBCrudPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
                - Statement:
                    -
                        Action: [ 'ssm:GetParameter', 'secretsmanager:GetSecretValue' ]
                        Effect: Allow
                        Resource: '*'
                - Statement:
                    -
                        Action: [ 'states:SendTaskSuccess', 'states:SendTaskFailure' ]
                        Effect: Allow
                        Resource: '*'
            Layers:
                - !Ref layerXray
                - !Ref layerGrimreapercommon
                - !Ref layerRequests
            Environment:
                Variables:
                    STAGE: !Ref stage
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing

    functionUserDeactivator:
        Type: AWS::Serverless::Function
        Properties:
            Description: Deactivates Slack users
            CodeUri: ../../sam/functions/grimreaper-deactivator
            Timeout: 180
            Tracing: Active
            Policies:
                - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
                - DynamoDBCrudPolicy:
                    TableName: !Ref dynamodbTableUserProcessing
                - Statement:
                    -
                        Action: [ 'ssm:GetParameter', 'secretsmanager:GetSecretValue' ]
                        Effect: Allow
                        Resource: '*'
            Layers:
                - !Ref layerXray
                - !Ref layerGrimreapercommon
                - !Ref layerRequests
            Environment:
                Variables:
                    STAGE: !Ref stage
                    USER_PROCESSING_TABLE: !Ref dynamodbTableUserProcessing

Outputs:
    functionUserListArn:
        Value: !GetAtt functionUserList.Arn
        Description: Lambda function functionUserList Arn
    functionAdLookupArn:
        Value: !GetAtt functionAdLookup.Arn
        Description: Lambda function functionAdLookup Arn
    functionSummarizerArn:
        Value: !GetAtt functionSummarizer.Arn
        Description: Lambda function functionSummarizer Arn
    functionSlackMessengerArn:
        Value: !GetAtt functionSlackMessenger.Arn
        Description: Lambda function functionMessenger Arn
    functionUserDeactivatorArn:
        Value: !GetAtt functionUserDeactivator.Arn
        Description: Lambda function functionUserDeactivator Arn
